# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86be98ace0877e64654fd3c2ffa824d776233fefae72d07e1dd2119899d0557bc72336121cfa2f6838be993e7e385487e5b913f267696239d8bad03b86ddf264

test:
  secret_key_base: 9e833f2a01568ed00668021028f6b7aa6f492036d19b9dd0f332293b001ca5d55c89e736065aba116b1edf3a2377376c1e09a494a2d4e113fdb0f89c254e73b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
